Failing without version

diff --git a/check b/check
--- a/check
+++ b/check
@@ -3,4 +3,9 @@ set -eu
 
 version=$(echo -n -e '\x01\x06' | nc -q 3 spectrum-patch-ipv4.pathofexile.com 12995 | cut -d "/" -f 6 | iconv -f UTF-16BE)
 
+if [ -z "$version" ]; then
+  echo "could not get version"
+  exit 1
+fi
+
 echo "[{\"version\":\"$version\"}]"
